name: Build Desktop GUI
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  make

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  make
        
  Windows:
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  nmake
