name: Build Desktop GUI
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  make

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2
        
      - run:  mkdir build

      - name: QMake
        run: cd build && qmake ../AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  cd build && make
        
      - name: MacDeployQT
        run:  cd build && macdeployqt AWAH-SIP_Desktop-GUI.app -dmg
        
      - run:  ls -l
        
  Windows:
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  nmake
        
      - name: WinDeployQT
        run:  cd release && windeployqt --release --no-translations --compiler-runtime AWAH-SIP_Desktop-GUI.exe
        
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: .
          dest: AWAH-SIP_Desktop-GUI-${GITHUB_SHA}.zip
