name: Build Desktop GUI
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: mkdir build && cd build && qmake CONFIG+=release PREFIX=/usr ../AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  cd build && make -j$(nproc)
        
      - name: MakeInstall
        run:  cd build && make INSTALL_ROOT=appdir -j$(nproc) install
        
      - name: LinuxDeployQT
        run:  find appdir/
              wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
              chmod a+x linuxdeployqt-continuous-x86_64.AppImage
              # export VERSION=... # linuxdeployqt uses this for naming the file
              ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -verbose=2
  
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2
        
      - run:  mkdir build

      - name: QMake
        run: cd build && qmake ../AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  cd build && make && mv AWAH-SIP_Desktop-GUI.app AWAH-SIP_Desktop-GUI_${{ github.sha }}.app
        
      - name: MacDeployQT
        run:  cd build && macdeployqt AWAH-SIP_Desktop-GUI_${{ github.sha }}.app -dmg
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AWAH-SIP_Desktop-GUI_${{ github.sha }}.dmg
          path: build/AWAH-SIP_Desktop-GUI_*.dmg
        
  Windows:
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  nmake
        
      - name: WinDeployQT
        run:  md deploy && copy release\AWAH-SIP_Desktop-GUI.exe deploy\ && windeployqt --release --no-translations --compiler-runtime deploy\AWAH-SIP_Desktop-GUI.exe
        
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: deploy
          dest: AWAH-SIP_Desktop-GUI-${{ github.sha }}.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AWAH-SIP_Desktop-GUI-${{ github.sha }}.zip
          path: AWAH-SIP_Desktop-GUI-*.zip
