name: Build Desktop GUI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: QMake
        run: qmake AWAH-SIP_Desktop-GUI.pro
        
      - name: Make
        run:  |
              if [ "$RUNNER_OS" == "Windows" ]; then
                  nmake
              else
                  make
              fi
        shell: bash
        
